services:
  ffc-sfd-data:
    build:
      context: .
      target: production
    image: ffc-sfd-data
    container_name: ffc-sfd-data
    depends_on:
      - ffc-sfd-data-redis
      - ffc-sfd-data-postgres
      - ffc-sfd-data-cosmos-db
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-data-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      APIM_CLIENT_ID: ${APIM_CLIENT_ID}
      APIM_CLIENT_SECRET: ${APIM_CLIENT_SECRET}
      APIM_SCOPE: ${APIM_SCOPE}
      APIM_OCP_SUBSCRIPTION_KEY: ${APIM_OCP_SUBSCRIPTION_KEY}
      APIM_AUTHORIZATION_URL: ${APIM_AUTHORIZATION_URL}
      APIM_HOST_EXTERNAL: ${APIM_HOST_EXTERNAL}
      APIM_HOST_INTERNAL: ${APIM_HOST_INTERNAL}
      COSMOS_ENDPOINT: ${COSMOS_ENDPOINT:-https://ffc-sfd-data-cosmos-db:8081}
      COSMOS_KEY: ${COSMOS_KEY:-C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==}
      REDIS_HOST: ffc-sfd-data-redis

  ffc-sfd-data-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc-sfd-data
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
  
  ffc-sfd-data-redis:
    image: redis:6.2.7
  
  ffc-sfd-data-cosmos-db:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    tty: true
    restart: always
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 5
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: true
      AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE:
