services:
  ffc-sfd-data:
    build:
      context: .
      target: production
    image: ffc-sfd-data
    container_name: ffc-sfd-data
    depends_on:
      - ffc-sfd-data-redis
    environment:
      APPINSIGHTS-CLOUDROLE: ffc-sfd-data-local
      APPINSIGHTS-CONNECTIONSTRING: ${APPINSIGHTS-CONNECTIONSTRING}
      APIM-CLIENT-ID: ${APIM-CLIENT-ID}
      APIM-CLIENT-SECRET: ${APIM-CLIENT-SECRET}
      APIM-SCOPE: ${APIM-SCOPE}
      APIM-OCP-SUBSCRIPTION-KEY: ${APIM-OCP-SUBSCRIPTION-KEY}
      APIM-AUTHORIZATION-URL: ${APIM-AUTHORIZATION-URL}
      APIM-HOST: ${APIM-HOST}
      REDIS-HOST: ffc-sfd-data-redis

  ffc-sfd-data-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc-sfd-data
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
  
  ffc-sfd-data-redis:
    image: redis:6.2.7
