services:
  ffc-sfd-data:
    build:
      context: .
      target: production
    image: ffc-sfd-data
    container_name: ffc-sfd-data
    depends_on:
      - ffc-sfd-data-redis
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-data-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      APIM_CLIENT_ID: ${APIM_CLIENT_ID}
      APIM_CLIENT_SECRET: ${APIM_CLIENT_SECRET}
      APIM_SCOPE: ${APIM_SCOPE}
      APIM_OCP_SUBSCRIPTION_KEY: ${APIM_OCP_SUBSCRIPTION_KEY}
      APIM_AUTHORIZATION_URL: ${APIM_AUTHORIZATION_URL}
      APIM_HOST_EXTERNAL: ${APIM_HOST_EXTERNAL}
      APIM_HOST_INTERNAL: ${APIM_HOST_INTERNAL}
      REDIS_HOST: ffc-sfd-data-redis

  ffc-sfd-data-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc-sfd-data
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
  
  ffc-sfd-data-redis:
    image: redis:6.2.7
