services:
  ffc-sfd-data:
    build:
      context: .
      target: production
    image: ffc-sfd-data
    container_name: ffc-sfd-data
    depends_on:
      - ffc-sfd-data-redis
      - ffc-sfd-data-postgres
      - cosmos-db
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-data-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      APIM_CLIENT_ID: ${APIM_CLIENT_ID}
      APIM_CLIENT_SECRET: ${APIM_CLIENT_SECRET}
      APIM_SCOPE: ${APIM_SCOPE}
      APIM_OCP_SUBSCRIPTION_KEY: ${APIM_OCP_SUBSCRIPTION_KEY}
      APIM_AUTHORIZATION_URL: ${APIM_AUTHORIZATION_URL}
      APIM_HOST_EXTERNAL: ${APIM_HOST_EXTERNAL}
      APIM_HOST_INTERNAL: ${APIM_HOST_INTERNAL}
      REDIS_HOST: ffc-sfd-data-redis
      COSMOS_ENDPOINT: ${COSMOS_ENDPOINT}
      COSMOS_KEY: ${COSMOS_KEY}
      COSMOS_MESSAGES_DATABASE: ${COSMOS_MESSAGES_DATABASE}
      COSMOS_MESSAGES_CONTAINER: ${COSMOS_MESSAGES_CONTAINER}

  ffc-sfd-data-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc-sfd-data
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
  
  ffc-sfd-data-redis:
    image: redis:6.2.7
  
  cosmos-db:
    container_name: cosmos-db
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    tty: true
    restart: always
    ports:
      - "8081:8081"
      - "10250:10250"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
      - "10255:10255"
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 5
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: true
      AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE:
    volumes:
      - cosmos_data:/var/lib/cosmosdb/data
        
volumes:
    cosmos_data:   
