- key: APPINSIGHTS-CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: APIM-CLIENT-SECRET
  value: "{{servicename}}-APIM-CLIENT-SECRET"
  type: "keyvault"
- key: REDIS-PASSWORD
  value: "{{servicename}}-REDIS-PASSWORD"
  type: "keyvault"
- key: APIM-CLIENT-ID
  value: "{{servicename}}-APIM-CLIENT-ID"
  type: "keyvault"
- key: APIM-SCOPE
  value: "{{servicename}}-APIM-SCOPE"
  type: "keyvault"
- key: APIM-OCP-SUBSCRIPTION-KEY
  value: "{{servicename}}-APIM-OCP-SUBSCRIPTION-KEY"
  type: "keyvault"
- key: APIM-AUTHORIZATION-URL
  value: "{{servicename}}-APIM-AUTHORIZATION-URL"
  type: "keyvault"
- key: APIM-HOST
  value: "{{servicename}}-APIM-HOST"
  type: "keyvault"
- key: REDIS-HOST
  value: "SNDADPINFRD3401.redis.cache.windows.net"
  type: "keyvault"
- key: REDIS-PORT
  value: "6380"