- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: APIM_CLIENT_SECRET
  value: "{{servicename}}-APIM-CLIENT-SECRET"
  type: "keyvault"
- key: REDIS_PASSWORD
  value: "{{servicename}}-REDIS-PASSWORD"
  type: "keyvault"
- key: APIM_CLIENT_ID
  value: "{{servicename}}-APIM-CLIENT-ID"
  type: "keyvault"
- key: APIM_SCOPE
  value: "{{servicename}}-APIM-SCOPE"
  type: "keyvault"
- key: APIM_OCP_SUBSCRIPTION_KEY
  value: "{{servicename}}-APIM-OCP-SUBSCRIPTION-KEY"
  type: "keyvault"
- key: APIM_AUTHORIZATION_URL
  value: "{{servicename}}-APIM-AUTHORIZATION-URL"
  type: "keyvault"
- key: APIM_HOST_EXTERNAL
  value: "{{servicename}}-APIM-HOST-EXTERNAL"
  type: "keyvault"
- key: APIM_HOST_INTERNAL
  value: "{{servicename}}-APIM-HOST-INTERNAL"
  type: "keyvault"
- key: REDIS_HOST
  value: "SNDADPINFRD3401.redis.cache.windows.net"
- key: REDIS_PORT
  value: "6380"
