#!/bin/bash

echo "Waiting for CosmosDB"

until wget --no-check-certificate --timeout=5 --tries=1 -O /dev/null -o /dev/null https://ffc-sfd-data-cosmos-db:8081/_explorer/index.html; do
    sleep 5;
    echo "Waiting for CosmosDB..."
done;

echo "Cosmos wait completed"
