#!/bin/bash
duration=$1
remaining=$duration
# echo "Waiting $duration seconds for Cosmos DB to be ready"


pwd
echo "Waiting for CosmosDB at..."
until curl --insecure --connect-timeout 5 --max-time 5 https://ffc-sfd-data-cosmos-db:8081/_explorer/index.html; do
    sleep 5;
    echo "Waiting for CosmosDB..."
done;
echo "Cosmos wait completed"

# while [ $remaining -gt 0 ]; do
#   if (( remaining % 10 == 0 )); then
#     echo "Cosmos wait: $remaining seconds remaining"
#   fi
#   sleep 1
#   ((remaining--))
# done

echo "Cosmos wait completed"
